/**
 * RateManu
 * API documentation
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from "../http/http";

export class CreateRatingRequest {
  /**
   * Will be generated if not provided
   */
  "id"?: string;
  "food": string;
  "rating": number;

  static readonly discriminator: string | undefined = undefined;

  static readonly attributeTypeMap: Array<{
    name: string;
    baseName: string;
    type: string;
    format: string;
  }> = [
    {
      name: "id",
      baseName: "id",
      type: "string",
      format: "uuid",
    },
    {
      name: "food",
      baseName: "food",
      type: "string",
      format: "uuid",
    },
    {
      name: "rating",
      baseName: "rating",
      type: "number",
      format: "",
    },
  ];

  static getAttributeTypeMap() {
    return CreateRatingRequest.attributeTypeMap;
  }

  public constructor() {}
}
