/**
 * RateManu
 * API documentation
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from "../http/http";

export class FoodResponse {
  "id"?: string;
  "name"?: string;
  "description"?: string | null;
  "author"?: string;
  "group"?: string;
  "createdAt"?: Date;
  "updatedAt"?: Date;

  static readonly discriminator: string | undefined = undefined;

  static readonly attributeTypeMap: Array<{
    name: string;
    baseName: string;
    type: string;
    format: string;
  }> = [
    {
      name: "id",
      baseName: "id",
      type: "string",
      format: "uuid",
    },
    {
      name: "name",
      baseName: "name",
      type: "string",
      format: "",
    },
    {
      name: "description",
      baseName: "description",
      type: "string",
      format: "",
    },
    {
      name: "author",
      baseName: "author",
      type: "string",
      format: "uuid",
    },
    {
      name: "group",
      baseName: "group",
      type: "string",
      format: "uuid",
    },
    {
      name: "createdAt",
      baseName: "createdAt",
      type: "Date",
      format: "date-time",
    },
    {
      name: "updatedAt",
      baseName: "updatedAt",
      type: "Date",
      format: "date-time",
    },
  ];

  static getAttributeTypeMap() {
    return FoodResponse.attributeTypeMap;
  }

  public constructor() {}
}
