/**
 * RateManu
 * API documentation
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { FoodResponse } from "../models/FoodResponse";
import { HttpFile } from "../http/http";

export class FoodCollectionResponse {
  "count"?: number;
  "items"?: Array<FoodResponse>;

  static readonly discriminator: string | undefined = undefined;

  static readonly attributeTypeMap: Array<{
    name: string;
    baseName: string;
    type: string;
    format: string;
  }> = [
    {
      name: "count",
      baseName: "count",
      type: "number",
      format: "",
    },
    {
      name: "items",
      baseName: "items",
      type: "Array<FoodResponse>",
      format: "",
    },
  ];

  static getAttributeTypeMap() {
    return FoodCollectionResponse.attributeTypeMap;
  }

  public constructor() {}
}
