/**
 * RateManu
 * API documentation
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from "../http/http";

export class UpdateRatingRequest {
  "rating": number;

  static readonly discriminator: string | undefined = undefined;

  static readonly attributeTypeMap: Array<{
    name: string;
    baseName: string;
    type: string;
    format: string;
  }> = [
    {
      name: "rating",
      baseName: "rating",
      type: "number",
      format: "",
    },
  ];

  static getAttributeTypeMap() {
    return UpdateRatingRequest.attributeTypeMap;
  }

  public constructor() {}
}
